
-- STATION
INSERT INTO STATION VALUES (1,'sol.d','Terre')
INSERT INTO STATION VALUES (2,'pegasi.b','Dimidium')
INSERT INTO STATION VALUES (3,'delphini.b','Arion')
INSERT INTO STATION VALUES (4,'cancri.c','Brahe')
INSERT INTO STATION VALUES (5,'epsilonTauri.b','Amateru')
INSERT INTO STATION VALUES (6,'gammaCepheiA.b','Tadmor')

-- MECANICIEN
INSERT INTO MECANICIEN VALUES (1,'meca1','mdpmeca1',1)
INSERT INTO MECANICIEN VALUES (2,'meca2','mdpmeca2',2)

-- USAGER
INSERT INTO USAGER VALUES (1,'usager1','mdpusager1')
INSERT INTO USAGER VALUES (2,'usager2','mdpusager2')

-- QUAI
INSERT INTO QUAI VALUES (1,1)
INSERT INTO QUAI VALUES (2,1)
INSERT INTO QUAI VALUES (3,1)
INSERT INTO QUAI VALUES (4,1)
INSERT INTO QUAI VALUES (5,2)
INSERT INTO QUAI VALUES (6,2)
INSERT INTO QUAI VALUES (7,3)
INSERT INTO QUAI VALUES (8,3)
INSERT INTO QUAI VALUES (9,4)
INSERT INTO QUAI VALUES (10,4)
INSERT INTO QUAI VALUES (11,5)
INSERT INTO QUAI VALUES (12,5)
INSERT INTO QUAI VALUES (13,6)
INSERT INTO QUAI VALUES (14,6)

-- NAVETTE
INSERT INTO NAVETTE VALUES (1,1,4,0,1)
INSERT INTO NAVETTE VALUES (2,1,4,0,2)
INSERT INTO NAVETTE VALUES (3,1,2,0,5)
INSERT INTO NAVETTE VALUES (4,1,2,0,7)
INSERT INTO NAVETTE VALUES (5,1,2,0,9)
INSERT INTO NAVETTE VALUES (6,1,2,0,11)
INSERT INTO NAVETTE VALUES (7,1,2,0,13)

